Added document listener to close foodTypes when not in focus
cheaper-eater/frontend pull request #10
Opened 2023-02-28 20:58 UTC by AlfredoSequeida

- Added document listener to close foodTypes when search bar is not in focus.
- Fixed the span width of location input TouchableOpacity.

2023-02-28 21:05 UTC, dani5612 commented on screens/index.js
> +  const searchBarRef = useRef(null);
I tried doing something like this but if you click anywhere on the screen that is not the search bar, it freezes the screen and crashes the site

2023-02-28 21:05 UTC, dani5612 commented on screens/index.js
> +  const searchBarRef = useRef(null);
it was something about it not being able to handle a null reference

2023-03-01 00:14 UTC, dani5612 approved these changes
This works! :D Thank you

2023-03-01 01:40 UTC, MayankTamakuwala requested changes
It would be nice if you would just get rid of those console logs on lines 78 and 82 in index.js. Other than that, functionality works. just need to integrate the search API endpoint.

2023-03-04 20:45 UTC, SeaWalks approved these changes

2023-03-04 20:47 UTC, MayankTamakuwala approved these changes

2023-03-04 20:47 UTC, merged